# Server configuration
server:
  port: 7080 #set your port
  http2:
    enabled: true

serviceUrl:
  chartService: https://dev.e-mint.in/chart
  validationServiceUrl: https://dev.e-mint.in/order-validation

# Spring Boot configuration
spring:
  profiles:
    active: development
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 5002
      database: 1
      connection-timeout: 500
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5487/emint?currentSchema=user_algo_service
    username: emint_develop
    password: develop-quant-654

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  cloud:
    function:
      definition: ksqlConsumer;
    stream:
      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:9092
          replicationFactor: 3
      bindings:
        ksqlConsumer-in-0:
          destination: dev-ksql-response
          group: algoService

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    com:
      emint: debug
    org:
      springframework: info