# Server configuration
server:
  port: 7080 #set your port
  http2.enabled: true

# Spring Boot configuration
spring:
  #  profiles:
  #    active: development
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      connection-timeout: 500
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5447/emint?currentSchema=algo_service&reWriteBatchedInserts=true
    username: emint_develop
    password: develop-quant-654

  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.jdbc.batch_size: 50

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    com.emint: debug
    org.springframework: info